hercules-ci-agent/hercules-ci-agent.cabal

This works even if g++ is not on PATH.
Might even work on a non-GNU toolchain, but that may be
wishful thinking.

hercules-ci-agent: Link C++ without g++ with -lstdc++

---

nix/default.nix
nix/packages.nix

Client injecting stuff like nix-gitignore is painful, unnecessary and
fragile - so we stop doing it.

nix: Pick fixed dependencies instead of injecting sources via overlay

---

tests/agent-test/src/Main.hs

The color codes mess up the interleaved
output on the test VM log.

tests/agent-test: Disable color

---

hercules-ci-api/src/Hercules/API/Projects/Job.hs

This breaks backward compatibility, but only the frontend is using that HTTP API for now.

Add GitCommitSource to a job

---

README.md
default.nix
hercules-ci-agent/hercules-ci-agent/Hercules/Agent.hs
nix/overlay.nix
shell.nix

Suppose the success event is recorded by the service, but the
response doesn't make it, this ensures that success xor failure
is reported.
Also it adds retries.

agent: Fix for potential partial success in task success

---

for-upstream-only/nixos/profiles/cache-keys-json.nix
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix.hs

Unfortunately urls are not normalized and that's upstream default.

cache.nixos.org should contain a trailing slash

---

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Token.hs

We'll have a dynamicSecretsDirectory later.
Having a `secrets` directory on the filesystem suggests that all secrets are there. This satisfies that expectation.

agent: Move session.key into base/secrets, independent of *static*SecretsDir

---

hercules-ci-api/hercules-gen-swagger/Main.hs
hercules-ci-api/swagger.nix

It was printed as a Haskell string
which is a funny thing
Parsers started throwing
because gen-elm was showing
— author unknown

api: Unquote the swagger output

---

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs

This will give us a bit better understanding where time is spent during eval.

Log when evaluator starts to push to cachix

---

hercules-ci-agent/hercules-ci-agent.cabal

Currently idle agent takes about 20-40% of CPU (with downscaled frequency), ~3% per each thread.
Disable parallel GC to save up CPU at the cost of bigger pauses.

Disable parallel gc to improve runtime performance

---

for-upstream/default.nixos.nix

Path units do not seem to be capable of restarting services, so
this introduces a oneshot service that is *started* and restarts
the actual service.
Closes #137

Fix nixos auto restart

---

for-upstream/deploy-keys.nix
hercules-ci-agent/CHANGELOG.md
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/BinaryCaches.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Config.hs
tests/agent-test.nix

- Provide the right error message for virtually everyone
- Less cognitive overhead in the module
Merging into netrc-use-trusted.

agent: Require binary-caches.json *file*

---

nix/ci.nix
nix/default.nix
nix/sources.json

Was expecting to shorten ci.nix, didn't happen but now:
- we have a `lib` in `ci.nix` which is nice
- adding targets scales better
- consistency with other projects (well, tbd :) )
Out of scope: DRY the default nixpkgs source choice.

nix/ci.nix: Use dimension function

---

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs

Fixes #170
Derivation size is really small, so we can have a higher default of concurrent workers for evaluation.

Increase eval push workers to 16

---

hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs

It didn't update right when a drv has to be rebuilt in quick succession, due to quick GC or fluke.

Worker: Use M.insert to avoid Monoid order mistake

---

nix/ci.nix
nix/packages.nix

The integration tests worked on a heavy aarch64 machine, but are not worth running on every push now.

Add aarch64-linux builds

---

for-upstream/default.nix-darwin.nix
for-upstream/default.nixos.nix
hercules-ci-agent/hercules-ci-agent/Hercules/Agent.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Config.hs
tests/agent-test.nix

Generalizes the config item and sets it in the NixOS and nix-darwin modules.
Refs https://github.com/hercules-ci/docs.hercules-ci.com/issues/102

agent: requireMaterializedDerivations -> nixUserIsTrusted

---

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cache.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/EnvironmentInfo.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Nix.hs

Makes `netrc-file` in `~hercules-ci-agent/.config/nix/nix.conf` work.

Add entries from ambient Nix netrc-file

---

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Init.hs
nix/cachix-api.nix
nix/cachix.nix
nix/nix-narinfo.nix
nix/packages.nix
scripts/generate-nix
stack.yaml

(cherry picked from commit baf170e8680531022aa4bbd968ae864b325d9bba)
Does not include write token support because it breaks config semantics.

cachix: 0.3.8 -> 0.5.1

---

nix/packages.nix

Produce useful coredumps if necessary.

hercules-ci-agent: enableDWARFDebugging

---

flake.lock
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build.hs
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build/Prefetched.hs
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Effect.hs
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/HerculesStore.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cache.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Env.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Init.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Nix/RetrieveDerivationInfo.hs
hercules-ci-cli/src/Hercules/CLI/Effect.hs
hercules-ci-cli/src/Hercules/CLI/Nix.hs
hercules-ci-cnix-expr/src/Hercules/CNix/Expr.hs
hercules-ci-cnix-store/hercules-ci-cnix-store.cabal
hercules-ci-cnix-store/include/hercules-ci-cnix/store.hxx
hercules-ci-cnix-store/src/Hercules/CNix.hs
hercules-ci-cnix-store/src/Hercules/CNix/Store.hs
hercules-ci-cnix-store/src/Hercules/CNix/Store/Context.hs
nix/cachix.nix
nix/packages.nix
scripts/generate-nix
stack.yaml

- Make hercules-ci-cnix-store suitable for cachix
- Use patched cachix to use that lib, removing unsafeCoerce
- Update to GHC 8.10.4 and Stackage LTS 17.5
- Enable some profiling builds

hercules-ci-cnix-store/cachix maintenance

---

nix/flake-compat.nix

nix/flake-compat.nix: Add hint because Nix 2.4 breaks flake-compat

---

hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build/Logger.hs
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Conduit.hs
hercules-ci-agent/hercules-ci-agent.cabal
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Effect.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Log.hs
hercules-ci-agent/src/Hercules/Agent/Socket.hs
hercules-ci-agent/test/Hercules/Agent/Worker/ConduitSpec.hs
hercules-ci-agent/test/Spec.hs
hercules-ci-api-agent/src/Hercules/API/Logs/LogEntry.hs

- Add client side log limit.
- Remove remaining (hidden) progress message from log stream.
- Add task id and more to worker process log context.
- Add a 30s handshake timeout, so the socket can't wait indefinitely for connection. Existing "ack" timeout and pings take over from there.

Log client robust

---

hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Evaluate.hs
hercules-ci-cli/src/Hercules/CLI/Nix.hs
hercules-ci-cnix-expr/src/Hercules/CNix/Expr.hs
hercules-ci-cnix-expr/src/Hercules/CNix/Expr/Schema.hs
hercules-ci-cnix-store/hercules-ci-cnix-store.cabal

2.9.0 is delayed in Nixpkgs because of a crash, so won't merge the actual pin upgrade until we have 2.9.1.
Can probably merge the CPP stuff before that though.

Nix 2.9 buildable

---

README.md

Github markdown doesn't seem to support multiline indented codeblocks?

readme: block quote the final commands to render better

---

nix/packages.nix

I pull in the hercules-ci overlay and noticed that I couldn't update nixpkgs because https://github.com/NixOS/cabal2nix/pull/546 made its way to the nixos-unstable branch.

Support building with old & new cabal2nix

---

hercules-ci-agent/CHANGELOG.md
internal/nix/nixos/default.nix
internal/nix/nixos/multi.nix

Didn't get `pkgsLLVM` or `libcxxStdenv` or `clangStdenv` to work, so we're stuck with a bad regex implementation for the time being.
Changing the stack size limit is sufficient for purs-nix to work. Fixes #445 
>  - Work around excessive stack use by libstdc++ regex [issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164)
The new limit of 256 MiB stack allows larger string inputs to be used.
This bug was triggered by purs-nix and possibly other Nix expression libraries that parse substantial files.

hercules-ci-agent/nixos: Increase stack limit

---

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cache.hs

Neither ssh nor ssh-ng seem to retry sufficiently for a mass-rebuild to complete.

Retry when pushing to a nix cache

---

docs/modules/ROOT/pages/agent-config.adoc
hercules-ci-agent/hercules-ci-agent/Hercules/Agent.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Config.hs
hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Init.hs

This allows a developer to try and debug Nix configuration issues, by seeing more of the Nix output when running the agent.

Allow setting Nix verbosity in config

---

flake.nix
hercules-ci-agent/data/default-herculesCI-for-flake.nix
tests/default-herculesCI-for-flake-test.nix

It has a different nixpkgs module. Didn't show up in testing because `ciSystems` wasn't set.

default-herculesCI-for-flake.nix: Fix darwinConfigurations + ciSystems

---

internal/nix/common.nix
tests/nix-darwin-example.nix

Detecting this at runtime is not possible yet, so we check statically.
Prevents a runtime error.

module: Make sure trusted-users does not shadow our setting

---

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs

It used to go to `/`, but that may fail on darwin:
/nix/store/gq3lh1gg4k16bwj42phgxzi3as47v45i-hercules-ci-agent-0.9.11/bin/hercules-ci-agent-worker: createProcess: chdir: invalid argument (Bad file descriptor)
-- https://hercules-ci.com/accounts/github/hercules-ci/derivations/%2Fnix%2Fstore%2Fim8z1s5g07qfkzz4f8blhd95wzrjgfnr-hercules-ci-cnix-expr-0.3.5.1.drv/log?via-job=3f8281d8-f0a7-4810-aee0-8a5a1f078bd8

hercules-ci-agent: Do not chdir the build worker

---

flake.nix

Probably not needed anymore, but causing issues because of a Nix bug in `getFlake`.
A haskell-flake update should also solve the problem, but let's merge the quick fix first.

maint: flake.nix: Drop releaser override

---

hercules-ci-agent/cbits/hercules-error.cxx
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build/Logger.hs
hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build/Prefetched.hs
hercules-ci-cnix-expr/src/Hercules/CNix/Expr.hs
hercules-ci-cnix-store/cbits/string.cxx
hercules-ci-cnix-store/hercules-ci-cnix-store.cabal
hercules-ci-cnix-store/include/hercules-ci-cnix/string.hxx
hercules-ci-cnix-store/src/Hercules/CNix.hs
hercules-ci-cnix-store/src/Hercules/CNix/Settings.hs
hercules-ci-cnix-store/src/Hercules/CNix/Store.hs

s.c_str() is only defined while s is in scope. Fine for variables, but unassigned return values cause undefined behavior.
This gets rid of almost all of the c_str() calls. A few remain, and those have been checked for this problem and are ok.

fix: Avoid s.c_str()
