hercules-ci/hercules-ci-agent

upstream-only-module.nix
rename, don't create user if overridden
=> module: Improve user config

tests/agent-test.nix, tests/agent-test/hercules-ci-agent-test.cabal
=> Rename hercules-agent-test -> hercules-ci-agent-test

hercules-ci-api/hercules-ci-api.cabal, nix/haskell-shell.nix, nix/packages.nix, nix/stack-shell.nix, stack.yaml
Previous expression mixed the Nixpkgs way of managing project dependencies and the Stack-Nix way.
This works well with my HIE setup.
=> Simplify stack

brittany.yaml
=> Add brittany formatter configuration

hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-agent/test/Spec.hs, hercules-ci-api/hercules-ci-api.cabal, hercules-ci-api/test/Spec.hs, tests/agent-test/src/Spec.hs
=> Remove hspec-discover dependency

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs
=> hercules-ci-agent: Add fixed timeouts to drv build

for-upstream-only/README.md
"Recommend" profile.nix instead.
=> for-upstream-only/README.md

hercules-ci-api/hercules-ci-api.cabal, hercules-ci-api/src/Hercules/API/Build/EvaluationDetail.hs, hercules-ci-api/src/Hercules/API/Evaluation/Evaluation.hs, hercules-ci-api/src/Hercules/API/Projects.hs, hercules-ci-api/src/Hercules/API/Projects/Job.hs
=> api: From [Attr] to EvaluationDetail

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Client.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Env.hs, hercules-ci-api/hercules-ci-api.cabal, hercules-ci-api/src/Hercules/API/Agent/Build.hs, hercules-ci-api/src/Hercules/API/Agent/Build/BuildTask.hs, hercules-ci-api/src/Hercules/API/Logs.hs
Includes agent despite the branch name.
=> New logs endpoint

default.nix, nix/default.nix, nix/packages.nix, nix/sources.json, stack.yaml, tests/agent-test.nix, tests/agent-test/hercules-ci-agent-test.cabal, tests/agent-test/src/MockTasksApi.hs
=> Update including LTS-13, restricting test-only code to LTS-13

hercules-ci-agent/hercules-ci-agent.cabal
=> Compile on darwin

nix/packages.nix, nix/sources.json
Stops the needless rebuilds when working on the project.
=> Use hercules-ci/gitignore

hercules-ci-agent/CHANGELOG.md, hercules-ci-agent/hercules-ci-agent.cabal
=> hercules-agent-0.2

for-upstream-only/nixos/modules/services/continuous-integration/hercules-ci-agent.nix, for-upstream-only/nixos/profiles/cache-keys-json.nix, for-upstream-only/nixos/profiles/hercules-ci-agent.nix, for-upstream-only/nixos/profiles/nixops-hercules-ci-agent.nix
=> agent: Update Nix glue for binary-caches.json

RELEASE.md, for-upstream/common.nix, for-upstream/default.nixos.nix, for-upstream/deploy-keys.nix, for-upstream/system-caches.common.nix, hercules-ci-agent/hercules-ci-agent/Hercules/Agent.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/BinaryCaches.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Init.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Config.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Env.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/EnvironmentInfo.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Init.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/SecureDirectory.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Token.hs, module.nix, tests/agent-test.nix
=> Introduce baseDirectory

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs
"Will rewrite this code without mutation later." - Robert, famous last words
=> Fix an IORef race

hercules-ci-agent/CHANGELOG.md
=> 0.3 release

hercules-ci-agent/pkg.nix, hercules-ci-api/pkg.nix, nix/cachix-api.nix, nix/cachix.nix, nix/ci.nix, nix/default.nix, nix/packages.nix, nix/sources.json, scripts/generate-nix, tests/agent-test/pkg.nix
=> Build for darwin

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Batch.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Scribe.hs
Not super urgent because it only happens when the service can't be reached.
=> Fix eval network exceptions propagation

for-upstream/default.nixos.nix
Same behaviour is already in nix-darwin to address #8
=> #8: restart agent on secrets change

module.nix
Resolves #32, still needs instructions to configure cachix.
=> pin nixpkgs for building hercules-ci-agent

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Env.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Init.hs, nix/cachix-api.nix, nix/cachix.nix, nix/packages.nix, nix/sources.json, stack.yaml
=> cachix: "0.2.1" -> master

hercules-ci-agent/hercules-ci-agent/Hercules/Agent.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs
Removes the "technical error" "status" from build failures.
=> Report build failure as such instead of exceptional

hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Config.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/EnvironmentInfo.hs, hercules-ci-api/hercules-ci-api.cabal, hercules-ci-api/src/Hercules/API/Agents/AgentInfo.hs, hercules-ci-api/test/Hercules/API/Agent/AgentInfoSpec.hs, hercules-ci-api/test/Spec.hs
Does not require service update (tested).
=> api,agent: Submit concurrentTasks

for-upstream/default.nixos.nix
Fixes https://github.com/hercules-ci/support/issues/29
=> use network-online.target to depend on configured networking

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs
Now:
```
[53231.520078] hercules-ci-agent[244]: [2019-10-27 10:19:36][][Debug][f2fc91b2abba][244][ThreadId 22][task:1b633978-dee1-47ae-88a3-d27c9e5e7853][task-type:build][agent-version:0.5.0][main:Hercules.Agent.Build hercules-ci-agent/Hercules/Agent/Build.hs:75:3] Building: RawCommand "nix-store" ["--realise","--timeout","36000","--max-silent-time","1800","--option","netrc-file","/var/lib/hercules-ci-agent/work/secure/tmp-netrc244-0.key","--option","substituters","https://cache.nixos.org/","--option","trusted-public-keys","cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=","--","/nix/store/i533ma209s40dmq3p6wcx2xbd85ygmw9-agent.drv"]
[53231.903978] hercules-ci-agent[244]: [2019-10-27 10:19:36][][Error][f2fc91b2abba][244][ThreadId …
```
=> Improve messaging around building

for-upstream/gc.nix
=> fix #150: enable min-free and max-free GC

for-upstream/default.nixos.nix
=> Issue 195 stop agent before network

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Env.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Init.hs
=> Use cachix-specific http client manager

for-upstream/common.nix, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs, hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/EnvironmentInfo.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Nix/Init.hs, hercules-ci-agent/src/Hercules/Agent/WorkerProtocol/Command/BuildResult.hs, hercules-ci-agent/src/Hercules/Agent/WorkerProtocol/Event.hs, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate.hs, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate/EvaluateEvent/BuildRequest.hs, tests/agent-test/src/EvaluationSpec.hs, tests/agent-test/src/MockTasksApi.hs
=> Add forced rebuilds + fixes

tests/module-nixos/configuration-3-nixops-binaryCachesFile.nix
It has caused some confusion: https://github.com/hercules-ci/support/issues/45
=> Clarify binaryCachesFile test case

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs
This feature will be replaced. Instead, use
import nixpkgs { system = "..."; }
=> Allow setting the default system in an ad-hoc way

hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build/Logger.hs
Also clean up a bit: removing a fd -> handle -> fd conversion and closing
the original stderr copy.
=> Work around missing EOF on worker stderr "tap"

.envrc, docs/modules/ROOT/pages/agent-config.adoc, docs/modules/ROOT/partials/agent-small-example.toml, hercules-ci-agent/CHANGELOG.md, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Config.hs, internal/nix/common.nix, templates/nixos/flake.nix
=> Set default concurrentTasks to number of cpu cores

hercules-ci-cli/src/Hercules/CLI/State.hs
=> hci state put: Confirm upload

hercules-ci-cli/src/Hercules/CLI/Effect.hs, hercules-ci-cli/src/Hercules/CLI/Project.hs
Lets you choose not to get an API token. Disallows access to state
files, but can run in untrusted environment or unconfigured repo.
=> hci effect run: Add --no-token

hercules-ci-agent/src/Hercules/Effect/Container.hs
=> effects: Fix error mkdir /run/runc: permission denied

flake.nix, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build/Prefetched.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Init.hs, hercules-ci-cli/src/Hercules/CLI/Nix.hs, hercules-ci-cnix-expr/src/Hercules/CNix/Expr.hs, hercules-ci-cnix-store/hercules-ci-cnix-store.cabal, hercules-ci-cnix-store/src/Hercules/CNix.hs, hercules-ci-cnix-store/src/Hercules/CNix/Store.hs, hercules-ci-cnix-store/src/Hercules/CNix/Util.hs
- Makes `hci effect run` interruptible during its preparation (fetching, building, etc)
- Some minor improvements
=> Improve interrupt handling

docs/modules/ROOT/pages/evaluation.adoc, docs/modules/ROOT/pages/legacy-evaluation.adoc, docs/modules/ROOT/partials/nav-items.adoc, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs, hercules-ci-agent/src/Hercules/Agent/NixFile/HerculesCIArgs.hs
Ugh, diff doesn't recognize the move of the legacy page.
=> Docs for new expression format

docs/modules/ROOT/pages/agent-config.adoc, hercules-ci-agent/CHANGELOG.md, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Config.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Effect.hs, internal/nix/common.nix
Known issue: module doc link will be fixed in 0.9.
=> Add secretsJsonPath in agent config

docs/modules/ROOT/pages/deployment-requirements.adoc, flake.lock, flake.nix, hercules-ci-agent/CHANGELOG.md, hercules-ci-agent/cbits/hercules-logger.hh, hercules-ci-agent/cbits/nix-2.4/hercules-store.hh, hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-cli/CHANGELOG.md, hercules-ci-cnix-store/compat-2.4/include/nix-compat.hh, nix/make-overlay.nix, nix/packages.nix, nix/stack-shell.nix, stack.yaml
=> Add aarch64 darwin, default Nix to 2.4

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs
This solves an error scenario where
1. The worker crashes. This has happened with Nix bugs.
2. Builds are created, assuming a partial build is useful.
3. Scheduler assumes drvs were uploaded.
4. Builds fail because of missing drv.
It solves the root cause for an instance of #314
=> Wait for all derivations to push, even if eval worker has crashed

hercules-ci-api-agent/test/Hercules/API/Agent/Evaluate/EvaluateEvent/DerivationInfoSpec.hs
=> Fix DerivationInfoSpec test

docs/modules/hci/pages/secret/add.adoc, docs/modules/hci/pages/secret/echo.adoc, docs/modules/hci/partials/create-secret-options.adoc, docs/modules/hci/partials/nav-items.adoc, hercules-ci-cli/src/Hercules/CLI/JSON.hs, hercules-ci-cli/src/Hercules/CLI/Secret.hs, nix/packages.nix, tests/cli.nix
(cherry picked from commit c2668953860adba5a74a05efd7dd068c6c4e1bf6)
=> Add hci secret echo command

docs/modules/ROOT/pages/binary-caches-json.adoc
=> Update CachixCache reference doc

hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs, hercules-ci-agent/src/Hercules/Agent/NixFile.hs, hercules-ci-agent/src/Hercules/Agent/WorkerProtocol/Command/Eval.hs, hercules-ci-api-agent/hercules-ci-api-agent.cabal, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate/EvaluateEvent/OnPushHandlerEvent.hs, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate/EvaluateTask.hs, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate/EvaluateTask/OnPush.hs, hercules-ci-cnix-expr/src/Hercules/CNix/Expr/Schema.hs, tests/agent-test/src/BuildSpec.hs, tests/agent-test/src/EvaluationSpec.hs, tests/agent-test/src/MockTasksApi.hs, tests/agent-test/testdata/ci-dot-nix-herculesCI/ci.nix, tests/agent-test/testdata/flake-onPush-functions/flake.nix
Fetch flake-based job source using Nix
=> Fetch like flake

flake.lock, flake.nix, hercules-ci-agent/cbits/nix-2.4/hercules-store.cxx, hercules-ci-agent/cbits/nix-2.4/hercules-store.hh, hercules-ci-cnix-expr/hercules-ci-cnix-expr.cabal, hercules-ci-cnix-expr/test/TestMain.hs, hercules-ci-cnix-store/hercules-ci-cnix-store.cabal, hercules-ci-cnix-store/src/Hercules/CNix/Store.hs, nix/packages.nix, nix/shellFor-cabal.nix
=> Nix update

hercules-ci-agent/CHANGELOG.md, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Env.hs, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Evaluate.hs, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/STM.hs, hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Init.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Init.hs, hercules-ci-agent/src/Hercules/Agent/WorkerProtocol/Event.hs, hercules-ci-agent/src/Hercules/Agent/WorkerProtocol/Event/AttributeIFD.hs, hercules-ci-agent/test/Hercules/Agent/Worker/STMSpec.hs, hercules-ci-agent/test/Spec.hs, hercules-ci-api-agent/hercules-ci-api-agent.cabal, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate/EvaluateEvent.hs, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate/EvaluateEvent/AttributeIFDEvent.hs, tests/agent-test/src/EvaluationSpec.hs, tests/agent-test/src/MockTasksApi.hs
Run a couple of builds at the same time during eval
=> Nonblocking ifd

hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker.hs, hercules-ci-agent/src/Hercules/Agent/Socket.hs
=> Fix handshake timeout

hercules-ci-agent/hercules-ci-agent.cabal, nix/packages.nix
Refs https://github.com/NixOS/nixpkgs/pull/174176
=> Missing header

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs
Part of fix for https://github.com/hercules-ci/support/issues/67
Allows builds with very large numbers of derivations.
=> Evaluate: only restrict attribute events

nix/packages.nix
Don't know if sufficient, but it's a step.
=> hercules-ci-cnix-expr: Fix expression for strictDeps

internal/nix/common.nix, internal/nix/nixos/default.nix, internal/nix/settings.nix, nix/packages.nix
Make more similar for easy release to Nixpkgs.
=> Sync with nixpkgs

nix/packages.nix, tests/agent-test/src/EvaluationSpec.hs
Otherwise error when cloning flake input with git+ssh url:
```
error: cannot run ssh: No such file or directory
```
=> Add openssh to bundledBins

cabal.project, dev/private.narHash, dev/private/flake.lock, flake.lock, flake.nix, hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-agent/hercules-ci-agent/Hercules/Agent.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Env.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix/Init.hs, stack.yaml
Update `flake.lock`. See the commit message(s) for details.
You may reset this branch by deleting it and re-running the update job.
git push origin :flake-update
=> `flake.lock`: Update

hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cachix.hs, nix/development.nix, nix/flake-cachix-dev.nix
Bors is having trouble today it seems so this just mirrors #526 
Attr diff lgtm https://hercules-ci.com/github/hercules-ci/hercules-ci-agent/jobs/2304/compare?baseId=26058637-d487-44da-ae7f-24c4562c3762
=> Cachix 1.6

hercules-ci-agent/CHANGELOG.md, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build.hs, hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Build.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Cache.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Env.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/EnvironmentInfo.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Evaluate.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Init.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/Memo.hs, hercules-ci-agent/hercules-ci-agent/Hercules/Agent/ResourceLimiter.hs, hercules-ci-agent/src/Hercules/Agent/Store.hs, hercules-ci-api-agent/hercules-ci-api-agent.cabal, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate/EvaluateEvent.hs, hercules-ci-api-agent/src/Hercules/API/Agent/Evaluate/EvaluateEvent/SubstitutionQueryResult.hs, internal/nix/nix-darwin/default.nix, stack.yaml, tests/agent-test.nix, tests/agent-test/hercules-ci-agent-test.cabal, tests/agent-test/src/MockTasksApi.hs
=> Find substitutes in eval

hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-cli/CHANGELOG.md, hercules-ci-cli/hercules-ci-cli.cabal, hercules-ci-cli/src/Hercules/CLI/Client.hs, hercules-ci-cli/src/Hercules/CLI/Lock.hs, hercules-ci-cli/src/Hercules/CLI/State.hs
> `hci state` Commands are now more robust, retrying when HTTP requests fail
=> `hci state`: retry http

hercules-ci-cli/src/Hercules/CLI/Client.hs, hercules-ci-cli/src/Hercules/CLI/Effect.hs, hercules-ci-cli/src/Hercules/CLI/Login.hs, hercules-ci-cli/src/Hercules/CLI/Nix.hs, hercules-ci-cli/src/Hercules/CLI/Project.hs
Add retries to the remaining requests. See #555
=> `hci` retries

docs/modules/ROOT/pages/agent-config.adoc, docs/modules/ROOT/pages/effects.adoc, docs/modules/ROOT/pages/effects/declaration.adoc, flake.nix, hercules-ci-agent/CHANGELOG.md, hercules-ci-agent/hercules-ci-agent/Hercules/Agent.hs, hercules-ci-agent/src/Hercules/Effect.hs, hercules-ci-agent/src/Hercules/Effect/Container.hs, hercules-ci-cnix-store/src/Hercules/CNix/Store.hs, tests/agent-test.nix, tests/agent-test/hercules-ci-agent-test.cabal, tests/agent-test/src/BuildSpec.hs, tests/agent-test/src/EffectSpec.hs, tests/agent-test/src/EvaluationSpec.hs, tests/agent-test/src/Main.hs, tests/agent-test/src/MockTasksApi.hs, tests/agent-test/src/TestSupport.hs, tests/agent-test/testdata/effect-alternate/default.nix, tests/agent-test/testdata/effect/default.nix
=> Effects virtual UID, readonly root and crun

hercules-ci-api-core/src/Hercules/API/DayOfWeek.hs, hercules-ci-api/hercules-gen-swagger/Main.hs, hercules-ci-api/src/Hercules/API.hs
I think I broke their validator, because it doesn't show errors anymore on https://editor.swagger.io/
This schema is mostly untested still.
=> Fix OpenAPI3 schema

internal/nix/common.nix, internal/nix/settings.nix
=> maint: Remove mdDoc

.gitignore, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Build/Logger.hs, hercules-ci-agent/hercules-ci-agent-worker/Hercules/Agent/Worker/Error.hs, hercules-ci-cnix-expr/src/Hercules/CNix/Expr.hs, hercules-ci-cnix-expr/src/Hercules/CNix/Expr/Typed.hs, hercules-ci-cnix-store/hercules-ci-cnix-store.cabal, hercules-ci-cnix-store/src/Hercules/CNix/Encapsulation.hs, hercules-ci-cnix-store/src/Hercules/CNix/Memory.hs, hercules-ci-cnix-store/src/Hercules/CNix/Std/String.hs, hercules-ci-cnix-store/src/Hercules/CNix/Store.hs, hercules-ci-cnix-store/src/Hercules/CNix/Store/Context.hs
> This may include one or two sites that didn't need this treatment, but it's ok for the code to be a bit more explicit.
=> Fix fptr usages

README.md
You can find it on the project page in the dashboard
=> README: Add badge

hercules-ci-agent/CHANGELOG.md, hercules-ci-agent/hercules-ci-agent.cabal, hercules-ci-cnix-expr/CHANGELOG.md, hercules-ci-cnix-expr/hercules-ci-cnix-expr.cabal, hercules-ci-cnix-store/CHANGELOG.md, hercules-ci-cnix-store/hercules-ci-cnix-store.cabal, scripts/releaser
=> Release 0.10.6
